services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acquisitions-app-prod
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env.production
    # environment:
    #   NODE_ENV: production
    restart: unless-stopped
